#! /usr/bin/env dash

case $1 in
    set) brightnessctl set $2 ;;
    up) brightnessctl set +5% ;;
    down) brightnessctl set 5%- ;;
esac

eww update BLIGHT="$(expr 100 '*' $(brightnessctl -m get) / $(brightnessctl -m max))"
